version: '3.7'
services:
  pwndrop:
    image: linuxserver/pwndrop:latest
    container_name: pwndrop
    hostname: pwndrop
    restart: unless-stopped
    volumes:
      - ../Data/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SECRET_PATH=/pwndrop
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.pwndrop.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.pwndrop.entrypoints=web-secure"
      - "traefik.http.routers.pwndrop.middlewares=default-headers@file"
      - "traefik.http.routers.pwndrop.service=pwndrop"
      - "traefik.http.routers.pwndrop.tls=true"
      - "traefik.http.services.pwndrop.loadbalancer.server.port=8080" # Proxied Port
